iphone:
	#rm -rf ~/dev/BOOK/code/chapter-10/findAFriend/www/*
	cp -r *.js *.html *.css ~/dev/BOOK/code/chapter-10/findAFriend/www/

android:
	cp -r *.js *.html *.css ~/dev/BOOK/code/chapter-10/findAFriend_android/assets/www/
